name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Build
        run: ./gradlew build
      - name: Check
        run: ./gradlew checkSortDependencies
      - name: Upload signed debug APK
        uses: actions/upload-artifact@v7
        with:
          name: lightning-browser-debug-${{ github.sha }}
          path: app/build/outputs/apk/**/debug/*.apk
          if-no-files-found: error
          retention-days: 14
